# Generated by Django 4.0.3 on 2022-03-17 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название фирмы')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации фирмы')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customUser', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, verbose_name='Описание заказа')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления заказа')),
                ('in_work', models.BooleanField(default=False, verbose_name='Заказ в работе')),
                ('is_done', models.BooleanField(default=False, verbose_name='Заказ в выполнен')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('workType', models.ManyToManyField(related_name='workType', to='app_1.firm', verbose_name='Вид работ')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=300, verbose_name='Вид работы')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='text',
        ),
        migrations.AddField(
            model_name='service',
            name='content',
            field=models.TextField(default=0, max_length=1000, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Work',
        ),
        migrations.AddField(
            model_name='service',
            name='firm',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='firm', to='app_1.firm', verbose_name='Фирма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='workType',
            field=models.ManyToManyField(related_name='work', to='app_1.firm', verbose_name='Вид работ'),
        ),
    ]
