# Generated by Django 4.0.3 on 2022-03-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_firm_order_worktype_remove_service_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firm',
            options={'verbose_name': 'Фирма', 'verbose_name_plural': 'Фирмы'},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'verbose_name': 'Вид работы', 'verbose_name_plural': 'Виды работ'},
        ),
        migrations.AlterField(
            model_name='service',
            name='workType',
            field=models.ManyToManyField(related_name='work', to='app_1.worktype', verbose_name='Вид работ'),
        ),
    ]
