# Generated by Django 4.0.3 on 2022-03-17 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_alter_firm_options_alter_worktype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='workType',
        ),
        migrations.AddField(
            model_name='service',
            name='workType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='work', to='app_1.worktype', verbose_name='Вид работ'),
            preserve_default=False,
        ),
    ]
