# Generated by Django 4.0.3 on 2022-03-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_remove_service_worktype_service_worktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='workType',
            field=models.ManyToManyField(related_name='workType', to='app_1.worktype', verbose_name='Вид работ'),
        ),
    ]
