# Generated by Django 4.0.3 on 2022-03-20 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0008_delete_orderinwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Принято к исполнению')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firmExecutor', to='app_1.firm', verbose_name='Фирма-исполнитель')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='app_1.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Заказ в работе',
                'verbose_name_plural': 'Заказы в работе',
                'ordering': ['-date'],
            },
        ),
    ]
